### ISSUE TITLE
Safari Layout Bug

### ISSUE THREAD

**Issue by mtmcfarl** [travis-ci/travis-crowd#102]
There is quite a large blank white space in Safari with the fork banner in the upper right.  I see a quick flash of styled text then it disappears.

**Comment by rkh** [comment]
Are you on Lion? What version of Safari? We can reproduce this in old versions on Snow Leopard but have no idea how to fix it.

**Comment by mtmcfarl** [comment]
Sorry about that.  I'm on Snow Leopard 10.6.8, running Safari Version 5.1.1 (6534.51.22).

**Comment by mtmcfarl** [comment]
Seems like its the twitter widget iframe thats blowing it up.  If I set display:none to the twttrHubFrame id then the site looks fine.  Not sure why the iframe is being a pain.

**Comment by rkh** [comment]
Right. That's pretty hard to solve. We would have to create our own widget. Nothing is driving people to the page like twitter at the moment.

**Comment by mtmcfarl** [comment]
So it seems to me that if you set the height to 0px and leave the rest that it seems to fix the issue.  Do you see the same?
