### ISSUE TITLE
Organize remote pairing hours and office visits

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#107]
All "Huge" donors and company sponsors are entitled for remote pairing hours or office visits (or alternative things)

**Comment by dmathieu** [comment]
What office ? (sorry for the dumb question. Can be replied by email).

**Comment by svenfuchs** [comment]
On https://love.travis-ci.org/company_packages you can see that platinum and gold packages are eligible for having us visit their offices :)

It's not clear yet, who wants to opt in there.

**Comment by sarahhodne** [comment]
Has this been done yet? Can we close this?

**Comment by rkh** [comment]
This has not happened yet. Though on the other hand, no one asked for this so far.
