### ISSUE TITLE
Add the bank account to the FAQ

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#20]

**Comment by fritzek** [comment]
Bank account info

BIC: WELADED1PMB
IBAN: DE37160500001000937166

German:
Mittelbrandenburgische Sparkasse Potsdam
BLZ: 16050000
KTO: 1000937166

**Comment by svenfuchs** [comment]
thanks :)

**Comment by svenfuchs** [comment]
added: http://travis-crowd-staging.herokuapp.com/#faq
