### ISSUE TITLE
Actually display an invoice

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#21]
Either directly on the order details show view or on a separate view.

What's legally required for that?

**Comment by fritzek** [comment]
First hint I've found we have to show as a (foot)note on the invoice is as follows:

```
Contributions and payments to travis-ci.org or Travis CI GmbH are not deductible as charitable 
contributions for federal income tax purposes. However, they may be deductible under other 
provisions of the Internal Revenue Code (for US) or your local tax authority's advice.
```

More follows.

**Comment by fritzek** [comment]
Ok, had a longer talk with my brother about this topic. He suggests to call the document "Receipt" as it is more of a confirmation about a payment than an invoice (implies business, trade or service). The purpose for the payment is a contribution to the travis-ci.org project to support ongoing development and operations. We should mention this on the receipt. This makes clear that the person gives the money for a purpose but not an obligation for service or goods (important for VAT regulations). The for-mentioned (last comment) paragraph should also be included.
So overall we should have the following on the document:
- who received the money -> Travis CI GmbH (with full address)
- who payed -> company or person (with full address) -> means, we need a validation
- date of receipt
- the receipt is for what -> contribution to travis-ci.org
- payment amount
- note about one off or subscription
- (foot)note (see above)

**Comment by fritzek** [comment]
My brother will do some further investigation to ensure his remarks are correct. I will contact our tax advisor and ask him too.

**Comment by svenfuchs** [comment]
cool. i guess we can display all of these things on the order/show page for now.

what do you mean by "we need a validation"?

**Comment by svenfuchs** [comment]
btw it is unclear if stripe also sends an "invoice"

**Comment by fritzek** [comment]
with validation i mean checking the presence of the address data

**Comment by svenfuchs** [comment]
hmmm, i'd like to keep that form as simple to fill out as possible. is it absolutely required legally that we know an address? you can pay for actual services on the web without filling in any addresses. Stripe will already validate the credit card account for us, so we have one of the best identity "validations" available (although we currently do not save the credit card holder's name).

**Comment by fritzek** [comment]
validating a credit card is no identity check - it proofs that the card works ;)

no idea about the legal requirement of full address existence - i just know from my experience and what my brother said its better to have it.
At least for the company packages I would validate the address as we're talking about money not peanuts ;)

**Comment by fritzek** [comment]
I suggest to validate the address for amounts > 100 USD (the 100 is the "border" in Germany to make invoice handling easier), subscriptions and comp packs

**Comment by svenfuchs** [comment]
It proofs that you have a valid card which is very attached to an identity. Also most banks check the card holder name if present.

**Comment by svenfuchs** [comment]
i'd not be very happy to add any more presence_of checks on the form unless we absolutely _know_ it's required legally.

requirements like these are raising barriers for people who want to donate. making people enter tons of data is known to make people click away quite often.

**Comment by fritzek** [comment]
ok, will ask someone + wait for my bro's further investigation (left a note about  it with him)

**Comment by svenfuchs** [comment]
awesome, thank you @fritzek <3

**Comment by svenfuchs** [comment]
@fritzek btw here's what the stripe account activation page looks like:

https://skitch.com/svenfuchs/gs5q6/stripe-manage
https://skitch.com/svenfuchs/gs5q9/stripe-manage-2

... so you can show that to any tax/lawyer folks

**Comment by svenfuchs** [comment]
The note "This will appear on your customer's statements" actually suggests that Stripe will send out invoices/statements

**Comment by svenfuchs** [comment]
So, all in all it seems to me that _if_ Stripe sends out invoices for us then they probably must have Jeff's name on them. 

If so the only thing we need to do is explain this on the order/new form loud and clear so people don't get confused. Afterwards we can internally bill Jeff and that's it?

**Comment by svenfuchs** [comment]
Address fields are now required for companies

**Comment by svenfuchs** [comment]
@joshk @fritzek It just occured to me that the invoicing issue is even _way more_ complicated IF 1. stripe does not send out invoices AND 2. we are legally required to send invoices for payments.

Because: in that case we need to send out an invoice once per month as long as the subscription exists.

Can we _please_ find a simpler solution to this.

**Comment by fritzek** [comment]
@svenfuchs no, its not necessary to send out a monthly invoice for subscriptions. You have to clearly mark on the invoice that it is a subscription and that the payment is on a monthly base. The payment receipt (and that is what I understood will be send out by Stripe) is the accounting document for the payee every month. Imagine an invoice for leasing a car - you only get one invoice and every month a direct debit payment with a reference to the leasing invoice on the bank statement.

**Comment by svenfuchs** [comment]
Ok, that sounds better.

The order confirmation email now looks like this: https://skitch.com/svenfuchs/g2d56/travis-crowd-order-confirmation-email

Will add all the legal notes next.

**Comment by fritzek** [comment]
looks perfect for the one off

**Comment by svenfuchs** [comment]
Legal notes and note about Jeff being our clearing agent added: https://skitch.com/svenfuchs/g2rwu/subscription-confirmation-email

I think I can now close this issue?
