### ISSUE TITLE
web site field needs default or desc

### ISSUE THREAD

**Issue by fritzek** [travis-ci/travis-crowd#3]
I've typed into the web site field just the name of the web site ("www.cileos.com") which will be interpreted as a relative link in the profile and overview page
solution 1: default the URI prefix ("http://") or make a tooltip with example

**Comment by svenfuchs** [comment]
lol, you should know that www.foo.com is not a valid url

hrmmm, ok, i'll try to add it

**Comment by fritzek** [comment]
I know its not a valid url but from my experiences a lot people just typing the name of their web site in. I'm sure if we don't change it, it will be a common problem.

**Comment by svenfuchs** [comment]
should be done

**Comment by fritzek** [comment]
thx. exactly what i meant ;)
