### ISSUE TITLE
scrollbar visibly on package badges on lower resolution

### ISSUE THREAD

**Issue by fritzek** [travis-ci/travis-crowd#34]
on a 15" screen with a resolution of 1440x900 the package badges show a scrollbar:

![Screenshot](http://img341.imageshack.us/img341/7067/screenshot20120110at133.png)

**Comment by rkh** [comment]
What browser are you using? Are you on latest master? This should have been fixed by e91be1dcae763a4d84d8204977883cc9af2fed10.

**Comment by fritzek** [comment]
I test on staging. If latest master is deployed on staging ...
I test with chrome, ff and safari

**Comment by svenfuchs** [comment]
should be fixed on staging
