### ISSUE TITLE
Add access to ringtones and sounds downloads

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#35]

**Comment by rkh** [comment]
Ringtones can be found under [/profile/ringtones](http://travis-crowd-staging.herokuapp.com/profile/ringtones). This page might need some more love and is not reachable unless you know the address.

Downloads itself work (only accessible when logged in) and come directly from Soundcloud/Amazon.

**Comment by svenfuchs** [comment]
w00t :)

**Comment by rkh** [comment]
Just added a link to the profile page. @svenfuchs could you improve the looks of the download page a bit?
