### ISSUE TITLE
Wording: "one off"

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#37]
Fernando finds it confusing, what's a better word?

I think "subscription" is good. What's a short and good word for "one time payment"

**Comment by svenfuchs** [comment]
Changed the text on the switch to "One payment" vs "Subscription" for now.

"One off" is still being used in the explanations on the homepage and on the form.

Any comments on those?

**Comment by joshk** [comment]
Single Purchase ?

**Comment by svenfuchs** [comment]
We were thinking "purchase" doesn't sound too much like commercial, shopping, products

We now use "Single Payment"
