### ISSUE TITLE
More or less payment options?

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#38]
Fernando says: "Too many options (between suscription and unique are 8 options". Tim on the other hand proposes to have more fine-grained and smaller payment options ("$1 -- $3 -- $7 -- $15 -- $25 -- $40")

**Comment by rkh** [comment]
The main issue with Tim's suggestion is that the cost for sending out stickers and such would be more than the donation. Maybe drop the Small option, rename Tiny to Small, add a Tiny with a $1 donation that basically comes with no specials except that they'll appear in the donation list and can leave a comment there.

**Comment by joshk** [comment]
1 buck payments would be eaten away by fees.

I am -1 on Tims payment suggestions

Maybe a 3 dollar payment with no stickers and just love, but then we have 6 plans which is too much imo.

**Comment by svenfuchs** [comment]
Ok, let's just keep what we have now and see what feedback we get. If LOTS of people want to donate smaller amounts we could also just add Flattr, Pledgie or similar
