### ISSUE TITLE
Reverse order of payment options?

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#39]
Fernando: "I have read somewhere that is good idea to start a list of prices from the most expensive, everything else looks cheap in comparation"

**Comment by joshk** [comment]
hmmmm, seems plausible, i like the layout now, wdyt?

**Comment by svenfuchs** [comment]
ok, I'll try this out

**Comment by svenfuchs** [comment]
done. @joshk wdyt? we're in favor of keeping it

**Comment by fritzek** [comment]
+1 for desc order

**Comment by svenfuchs** [comment]
bingo, we're all happy over here, too. closing this.
