### ISSUE TITLE
Less required fields on the form

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#40]
Fernando: "I can make an 'unique' donation but I have to fill a very big form. Password? Address? what for?"

and: "Why I have to fill all this data for an unique donation? or even for a suscription: address?"

I think he is right.

**Comment by svenfuchs** [comment]
How do we deal with this?
- We only need the address when people want us to send stickers (ie we could make it optional).
- We only need the user name/email/password data if people want to sign in later

They definitely want to sign in later in order to cancel a subscription. I.e. we could make it optional for one-off-payments

**Comment by rkh** [comment]
Alternative to name/password would be to send an e-mail with a link to creating a regular account. However, if that mail doesn't get through, they're screwed.

**Comment by joshk** [comment]
i think we should always grab the email in case we need to send them something important, maybe tax or receipt related.

as for address, maybe just say 'we need your address for stickers, no address no swag'

**Comment by svenfuchs** [comment]
I think this is still a nice-to-have things, but it's not totally required. We have to push a bit, so I'll tag it that way and move on for now
