### ISSUE TITLE
Fix validation error messages

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#43]
Fernando: "The field error messages apear one by one."

**Comment by svenfuchs** [comment]
I think what Fernando means here is the Chrome behavior for html5 required inputs? I'm not sure how to fix this. We could obviously replace it with some custom JS stuff.

**Comment by joshk** [comment]
Hmmm, I agree with Fernado, we really should find a way to show all the errors at once.

**Comment by svenfuchs** [comment]
In that case we can't use html5 browser form features and that means we'd need to either reimplement them or just skip them entirely

i am -1 on this tbh

**Comment by rkh** [comment]
:-1:

**Comment by rkh** [comment]
closing for now
