### ISSUE TITLE
Improve form field placeholders

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#44]
Fernando: "Twitter" field has a placeholder with an "@" should I insert the "@" in the info I write on it?.. same with "Homepage" and "http://"

... well, these are just the Chrome behavior for html5 inputs. Could spice that up with some JS of course

**Comment by joshk** [comment]
+1 on leaving @ and http:// in the respective fields

**Comment by rkh** [comment]
values are now prefixed by the model, which makes more sense imo.
