### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#46]

**Comment by rkh** [comment]
:+1:

possibly make it SSL only

**Comment by rkh** [comment]
Staging now forces SSL. We still have some resources loaded that are not SSL.

**Comment by rkh** [comment]
All but about 50% of the @soundcloud player is SSL now.

**Comment by joshk** [comment]
+1 on SSL only

We need to buy a cert for the production url we decide to use.

**Comment by rkh** [comment]
Some soundcloud devs are looking into the issue. Apparently they don't have a certificate for some asset host they are using.

**Comment by svenfuchs** [comment]
Ok, so this is done. Do we need to buy an SSL certificate for love.travis-ci.org? @joshk?

**Comment by svenfuchs** [comment]
hmmm, getting an annoying ssl warning there

is it possible to add a certificate to love.staging.travis-ci.org, too? or should we just continue to use travis-crowd-staging.herokuapp.com for staging?

**Comment by joshk** [comment]
Ssl certs cost $, so it's your pick on what URL for staging. 

I hope to have prod done tonight. 

J

---

**Comment by svenfuchs** [comment]
Ah, ok. Well, let's just use travis-crowd-staging.herokuapp.com then

**Comment by joshk** [comment]
done and done
