### ISSUE TITLE
Complete tool tips?

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#48]
Fernando: "Some fields has a helper message when you pass over them, someothers no, don't understand the logic."

... I've only added them to where I felt it's required. Not sure what to do?

**Comment by joshk** [comment]
I agree that it might seem odd that some have tool tips and some don't, especially as it doesn't seem like twitter or github need one. But this is a minor issue so -1 on fixing

**Comment by svenfuchs** [comment]
Ok, closing this
