### ISSUE TITLE
Make the page more gender neutral

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#49]
Jon: "My only feedback is that I have a niggling concern that with such extensive use of terms such as 'bro' and 'old chap' it might come across as not very gender-neutral."

**Comment by svenfuchs** [comment]
At the very least change wording like "Thank you, guys"

**Comment by rkh** [comment]
One idea would be to add ringtones/statements from female developers.

**Comment by svenfuchs** [comment]
Yeah, that would be the best solution. My problem there is that it would take us a lot of time. The ringtones previously only really got done when I visited Uwe in person (means travelling to lower saxony) and sat down with him for 2 days :/

It should be way easier to get some testimonials and add these.

And maybe we could contact rails-girls, rails-bridge and orgs like those and ask for help with new ringtones? that we'd then publish in a second round (i.e. after being live already)?

**Comment by svenfuchs** [comment]
I've made the testimonials list paginated and added a load of more testimonials (all dudes though). So we can now start to ask girls for testimonials and add a whole lot of them to the top.

**Comment by joshk** [comment]
what we have with the testimonials and wording in the titles seems good to me

**Comment by svenfuchs** [comment]
This is still work in progress. I think we're on a good way though and we can close this as a ticket.
