### ISSUE TITLE
cancel button of a subscription doesn't work

### ISSUE THREAD

**Issue by fritzek** [travis-ci/travis-crowd#5]
the cancel button of a subscription on profile page doesn't work (500)

**Comment by svenfuchs** [comment]
We might actually add a note asking users to send us an email. We'd then cancel subscriptions manually through the Stripe management interface.

**Comment by svenfuchs** [comment]
Strike that. People should be able to "downgrade" their subscription by cancelling it and ordering a new one.

For that more stuff needs to be changed though because right now one only can have one subscription. So subscriptions must be cancelled by "deactivating" them.

**Comment by svenfuchs** [comment]
Should work now.

When a user cancels their subscription the plan gets reset on Stripe and one can order a new subscription

**Comment by svenfuchs** [comment]
btw @fritzek i've had to reset the database and clear out all data on stripe

**Comment by fritzek** [comment]
ok, will give it a new try
