### ISSUE TITLE
Make more clear where the money goes

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#51]
Evan: "I'd suggest moving a section about what the money goes to toward the top of the page ... what they're getting for their money"

John: "communicate better for what you are actually collecting donations for, explain donation / project goals clearly in the beginning: Run Travis for free for open source projects and support the team and infrastructure."

John: "it could be more clear on the donation goals at first and add more fun later on in the text."

Peter: "Try and "sell" some of the benefits in the top section of the page. Not got enough time for specific suggestions here but rather than just asking for help, ask for help and hint or suggest that donors do get some benefit from it.. such as the new features you want to work on, the stickers, etc. Make it more into a "you get something awesome" feeling than a "help us!" thing."

**Comment by svenfuchs** [comment]
I've changed the text above the user packages a bit and added "What you will get?" as well as "What we'll use the money for?" in bold.

The latter paragraph now says:

```
%strong What we'll use the money for?
We are going to make Travis CI better (see <a href="#future-plans">some of the features</a> we have in the pipeline)
and we are going to build Travis CI pro<sup>2</sup>.
```

The footnote 2 already explains what Travis CI pro is.

I'm not sure what do do with Peter's suggestion though. Should we change the main headline ("We need your help!") to something else? Should we animate it?

**Comment by joshk** [comment]
+1 on your change, I think this is enough, if we get more feedback on twitter when we launch then maybe we can rethink

**Comment by svenfuchs** [comment]
Alright, closing this :)
