### ISSUE TITLE
Have recommendations from rails-core/other well-known members?

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#54]
John: "while the 4 heads are fun - maybe move some meaningful oneliners of known community members more to the top or closely to the donation / project goal"

**Comment by rkh** [comment]
That's what Brian's quote is for. Should we place more quotes there and make them cycle?

**Comment by joshk** [comment]
-1 i think what we have in the way of quotes and testimonials is fine

**Comment by svenfuchs** [comment]
Alright, closing this :)
