### ISSUE TITLE
Add flattr

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#55]
John and Sebastian: "add flattr"

**Comment by rkh** [comment]
we could add flattr, but I wouldn't offer any special gimmicks for it...

**Comment by svenfuchs** [comment]
that could be the replacement for the $1 donation, too?

**Comment by joshk** [comment]
-1 for flattr, i really don't know anyone using it

**Comment by svenfuchs** [comment]
It seems quite popular over here (two people already approached me in person about it)

There's also Pledgie.

It would just be a fallback that we could _link_ to (no crazy widgets) for people who say they don't like the "big" amount in the tiny package (i.e who want to donate less than 10 bucks)

Anyway. We can close this for now.
