### ISSUE TITLE
Sounds broken in webkit on 2nd click?

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#56]
Fabio: "When I klick on the nerd faces (Jon, José, Aaron or Yehuda) a second time there is no sound anymore. It works on Firefox"

**Comment by svenfuchs** [comment]
works for me in both Chrome and Safari :/

**Comment by rkh** [comment]
can't reproduce this either

**Comment by joshk** [comment]
can't reproduce, sometimes the sound is choppy and doesn't come out right, but it always kinda comes out

**Comment by svenfuchs** [comment]
Hrmmm, ok, so i'm gonna close this for now. Let's reopen it once we get more information about reproducing it
