### ISSUE TITLE
Find initial donors

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#59]
Peter: "Try to get the number of donors up a bit before pushing it live. Having just 1 donor doesn't look good. There's an annoying psychology effect at play here. If people see others have donated, they are more likely to. It's an annoying chicken and egg situation."

**Comment by rkh** [comment]
I'm not sure this will be an issue. We might just let more well known and enthusiastic people know before announcing it big time.

**Comment by svenfuchs** [comment]
should also use this as a brief beta test phase

**Comment by joshk** [comment]
i don't think this is an issue either, we just need to DM some friends and let them know we are launching this, or email the guys and girls who have given testimonials and we will be fine

**Comment by svenfuchs** [comment]
Alright, closing this :)
