### ISSUE TITLE
Explain vat and tax deduction

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#60]
Paolo: "questions about tax deduction of the donation, and VAT related amenities"

**Comment by svenfuchs** [comment]
We explain this on the order form already (which was 500'ing when Paolo reviewed the site). I've now also added an entry to the FAQ

**Comment by svenfuchs** [comment]
@fritzek can you please check the FAQ entry?

**Comment by fritzek** [comment]
@svenfuchs yep, will do it. Started to talk with my bro (again), but will ask our advisor too.
