### ISSUE TITLE
Include more languages

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#61]
Paolo: "too focused on ruby and ruby on rails"

**Comment by svenfuchs** [comment]
Not really sure what to do about this. I think that impression might result from:
1. We're listing more Ruby centric projects at the very top
2. We have that Rails-core team theme with the ringtones
3. We have testimonials mostly from Ruby/Rails folks

Re 1: That's just the actual big picture. We don't have as many super-important Node or PHP projects, yet, do we?

I'd opt for just ignoring this concern. We might actually add more non-ruby testimonials once we get them.

**Comment by rkh** [comment]
Yeah, I think the Ruby community is also where donations will come from.

**Comment by joshk** [comment]
making the site too generic would mean some people would not feel the attachment to the cause

I think leave it how it is

**Comment by svenfuchs** [comment]
Alright, closing this :)
