### ISSUE TITLE
Show subscriptions by default

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#63]
Alex: "assuming you prefer people to get a subscription over a one time donation I would make these available without having to click that switch (which is not very intuitive)."

Not sure about this one ...

**Comment by rkh** [comment]
I think subscriptions are something we should not confront people with before they are sold on the idea of donating.

**Comment by svenfuchs** [comment]
good point

**Comment by joshk** [comment]
-1 on showing subscriptions by default

**Comment by svenfuchs** [comment]
Alright, closing this :)
