### ISSUE TITLE
Shorten the text above packages

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#65]
Alex: "I don't think a lot of people will read the text above the packages (at least I didn't) - maybe shorten it or get rid of it."

**Comment by svenfuchs** [comment]
Not sure what to do about this. Since Alex reviewed the page I've even added more text above the packages to take care of other people's feedbacks.

**Comment by joshk** [comment]
-1 the new text you added is great, and the use of bold is perfect

**Comment by svenfuchs** [comment]
Alright, closing this :)
