### ISSUE TITLE
Make more clear what the rails core section is about

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#66]
Alex: "it's not clear what the 4 pictures of Yehuda etc. do - maybe add a headline above them?"

**Comment by svenfuchs** [comment]
Hmm, trouble is, a headline wouldn't really fit well with the design right now.

What would this headline or explanation say?

**Comment by rkh** [comment]
"Even the Rails Core team is exited about this?"

**Comment by joshk** [comment]
hmmm, valid point, i like Konstantins suggestion, but maybe we should change what the heads say to something nice about Travis?

**Comment by svenfuchs** [comment]
This would also help a tiny little bit with the gender issue.

@joshk so, Jon, José and Aaron all offered to record something new if needed. Could you please ask them to record a single, short sentence and recommend/ask/explain why to donate/that they're supporting this campaign?

**Comment by svenfuchs** [comment]
Not sure, is there anything going to happen with this?
