### ISSUE TITLE
Unhide the company packages

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#67]
Alex: "I wouldn't hide the company packages, instead make the 'thank you companies' section a lot smaller. that can grow after clicking, or you put the big version at the bottom."

**Comment by rkh** [comment]
dunno

**Comment by svenfuchs** [comment]
neither. i do actually like that they're hidden because this is not something most users care about.

**Comment by joshk** [comment]
-1 maybe change the 'show' text to 'how do i sponsor?'

**Comment by svenfuchs** [comment]
Ok, changed it that way

Closing this
