### ISSUE TITLE
Show the stickers more early

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#70]
Alex: "put the stickers next to the packages so you can see what you will get for donating."

**Comment by svenfuchs** [comment]
Basically every one suggests to move different things more towards the top :) Unfortunately we can't have everything at the top.

We have a link that links to the stickers section. I believe this is good enough. Any other ideas?

**Comment by rkh** [comment]
I think the page is fine the way it is organized.

**Comment by joshk** [comment]
-1 on moving stickers higher

**Comment by svenfuchs** [comment]
Ok, closing this.
