### ISSUE TITLE
Slider borked

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#72]
See the stripe.com slider (Paul)

**Comment by rkh** [comment]
Does he mean the slider should be animated? That's the only difference I see when comparing it to the stripe slider.

**Comment by joshk** [comment]
Only issue for the slider for me is that my cusor is not a hand but an arrow

**Comment by svenfuchs** [comment]
Arrrrgh. The CSS value for the attribute "cursor" that represents a hand is not "hand" but "pointer". The value that represents a pointer (i.e. an arrow) is "default"

I guess that's another CSS property where Microsoft got it right and the W3C got it wrong. I can _never_ remember that.

Fixed and closing this
