### ISSUE TITLE
Layout broken on ipad

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#73]
Unfortunately I don't have one to test :/

**Comment by rkh** [comment]
:+1:

**Comment by joshk** [comment]
hmm, +1 and -1

can Railslove help with this? cc/@bumi

**Comment by paulkoegel** [comment]
hey, here's some quick results of what I found out:

# Safari on iPad:
- page is white up to the heads.
- layout doesn't break with deactivated javascript.
- debug console:
  - JS error in line 1 - "Unsafe JavaScript attempt to access frame with URL http://travis-crowd-staging.herokuapp.com/# from frame with URL https://m.google.com/app/plus/poswidget/?hl=en[...]
  - HTML error in line 3 - "https://facebook.com/plugins/like.php?[...] Viewport argument value 'device-width'; for key 'width' not recognized. Content ignored.

will investigate further soon =)

**Comment by paulkoegel** [comment]
screenshot: http://imgur.com/okCSV

**Comment by svenfuchs** [comment]
Hmm, I simplified the layout a bit recently (now doing the margin: 0 auto center thing once, not N times) but that didn't seem to fix anything.

Somehow I feel it's about the iframe that the Twitter script injects at the top of the page.
