### ISSUE TITLE
Weird shaking behaviour on 11" screens

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#76]
Paul says:

"I'm getting a weird shaking behaviour when I move my mouse over to the
left of the screen. Is that intentional? "

"I'm in Safari 5.2.1 on a Macbook Air 11" … it happens when I scroll
off the main column into the sidebar. It doesn't happen if the browser
window takes up the whole screen."

**Comment by joshk** [comment]
I think this was the same issue I was getting with the speech bubbles when you first added them.

(I have an 13" screen)
