### ISSUE TITLE
Make more clear that there's a company behind it

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#77]
Reopened.

"people will ask themselves the question "who are you actually?" at the
moment they press/think about pressing the pay/donate button so I'd
try to have handy at that moment."

Is what we have enough? How can we improve it without overloading the packages section (which is already pretty packed)?

**Comment by rkh** [comment]
I think the main audience is people already knowing Travis...

**Comment by svenfuchs** [comment]
They might not know we're a company though ...

**Comment by fritzek** [comment]
we have mentioned twice that a company is behind this campaign (as footnote in reference to Travis Pro and in the FAQ).
the only really missing thing is an imprint (which is mandatory as of TMG §6) at the bottom

**Comment by svenfuchs** [comment]
@fritzek can you specify what needs to be there? (or link to an example imprint that we can copy from)

**Comment by svenfuchs** [comment]
@fritzek added a new ticket for this: #84

**Comment by svenfuchs** [comment]
Ok, closing this. Doesn't seem to be the most important thing.
