### ISSUE TITLE
Comment/Message fields are ambiguous

### ISSUE THREAD

**Issue by pat** [travis-ci/travis-crowd#78]
Josh clarified them for me, but you really should make that clear on the payment page.

**Comment by svenfuchs** [comment]
@freelancing-god We are going to rename them to "private" and "public" comment. Do you think that will clarify it?

**Comment by pat** [comment]
It certainly helps, but there's still the issue (currently) that you've got to mouse over the fields to see the hints. I'd personally have them constantly visible as paragraphs above each text box, and maybe make the labels less ambiguous (Public Comment, Message to the Travis Team, perhaps?)

**Comment by svenfuchs** [comment]
I've made the paragraph above both fields more descriptive. I've also tried to split the paragraph into 2 and have them above each field, but couldn't get it work visually (the form has the problem that the labels are aligned on the right side).

I think as we now have the information 3x there, that should work, even if still not perfect.

wdyt?

**Comment by pat** [comment]
If it was me, I'd put a paragraph above each field (para, field, para, field) - but could be I'm being too pedantic - probably not worth stressing about this too much :)

**Comment by svenfuchs** [comment]
i know what you mean :) and i'd prefer that, too. but it would need to work visually well, too (which is what i am too pedantic about ;) ... and that would require quite some work on the css

thanks for all your feedback, pat!
