### ISSUE TITLE
Why is a password needed?

### ISSUE THREAD

**Issue by pat** [travis-ci/travis-crowd#79]
I've been told it's so I can view my receipt - is it not possible to just have a link with a hash in the email to get to that? At the very least, I don't think it should be required, and it should be clear why it's being asked for.

**Comment by svenfuchs** [comment]
Well, there are a bunch of reasons why it's just easier to have a login and profile page.

I agree we might make it optional (that's some work though) AND we should explain it better.

**Comment by svenfuchs** [comment]
ALSO, thank you for your feedback @freelancing-god :D <3 <3 <3 <3
