### ISSUE TITLE
can't do a second donation after login

### ISSUE THREAD

**Issue by fritzek** [travis-ci/travis-crowd#8]
I've applied for a subscription and went back to landing page and pressed again the donate button for a one off donation; name field was filled, left all others blank, pressed confirm - button greyed out, nothing happened - just the cancel button worked

OT: #7 mentioned sign out not working - sign out on this page works

**Comment by svenfuchs** [comment]
should be fixed. you shouldn't be able create a new subscription when you already have one. instead you'll be redirected to the homepage with a flash message

**Comment by fritzek** [comment]
How about I have a subscription and want to add a one off donation?

**Comment by svenfuchs** [comment]
That should be possible

**Comment by fritzek** [comment]
nope. log in, choose one off, you will see your name (on the next page, but without your other data like street etc.), add a comment (or leave it blank) and press "Confirm" -> color of button changes to grey, but nothing else happens (you only can press "Cancel")

**Comment by svenfuchs** [comment]
there was another issue with the js form, should be fixed now

**Comment by fritzek** [comment]
works now (only -minor- issue -> the previously entered address data are lost - but guess we really talk about an edge case)

**Comment by svenfuchs** [comment]
wut? addresses are per order. 

do you mean we could prefill the address with the address from the previous/last order when the user is signed in? or something else?

**Comment by fritzek** [comment]
yes, if we still have it

**Comment by svenfuchs** [comment]
ok, i opened #18 for that
