### ISSUE TITLE
Add an imprint

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#84]
as mentioned in #77

**Comment by svenfuchs** [comment]
see http://www.cileos.com/imprint.html

**Comment by svenfuchs** [comment]
@fritzek see the imprint (link in the footer, content on https://travis-crowd-staging.herokuapp.com/imprint)

Will that work?

Closing this for now

**Comment by fritzek** [comment]
@svenfuchs looks good - will provide the missing data as soon I have them

**Comment by svenfuchs** [comment]
so, do we already have a tax number? maybe i should add some text there instead of the dots otherwise?

**Comment by fritzek** [comment]
no, we don't. we just have submitted at tax authority to get one. Not sure what you should leave instead. Maybe "In Gründung" too. Everyone in Germany knows it will take a while to get the stuff together.

**Comment by svenfuchs** [comment]
alright, perfect
