### ISSUE TITLE
Fix social links

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#85]
The "Please spread the word" widgets screw the design on the ipad, do not look perfect anyway and google+ 

Need to find someone who can help out with this

**Comment by svenfuchs** [comment]
Does this help? http://www.phpied.com/social-button-bffs/

**Comment by svenfuchs** [comment]
@bumi @skddc @rmehner would any of you guys be able to look into this?

:)

**Comment by svenfuchs** [comment]
re-added these links for now

**Comment by bumi** [comment]
@svenfuchs we've had a look at it in the emulator but we need a real ipad. 
will check it tomorrow with a real ipad same for the other issue @joshk  was referring to.

**Comment by svenfuchs** [comment]
w000t! thanks a ton, @bumi!!!
