### ISSUE TITLE
Add worker sponsors to logs

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-crowd#89]

**Comment by svenfuchs** [comment]
Done.

This is on staging and needs to be deployed (ideally all of workers, hub, web)

**Comment by svenfuchs** [comment]
@rkh can you take care of deploying this? can't assign you to this ticket right now (GH issue?)

**Comment by rkh** [comment]
Sure. I'll just have to figure out how to deploy on workers.

**Comment by svenfuchs** [comment]
we still do; `ssh ...; cd travis-worker; git pull;` and restart the worker :)

**Comment by rkh** [comment]
OK, seems fine to me. Thanks for the pointer.

**Comment by rkh** [comment]
All but the erlang worker + hub is deployed.

**Comment by svenfuchs** [comment]
awesome! anything holding the hub deployment back?

**Comment by rkh** [comment]
does hub depend on the worker changes?
