### ISSUE TITLE
Fix prices and desciptions for subscriptions

### ISSUE THREAD

**Issue by fritzek** [travis-ci/travis-crowd#9]
Subscription prices need to be displayed dynamically and the static descriptions need to be updated (put some thoughts into this, folks!)

**Comment by svenfuchs** [comment]
@fritzek i've edited the issue title and description directly

**Comment by svenfuchs** [comment]
Ok, prices are now updated dynamically for subscriptions and packages.

Still need to update the subscription texts OR maybe just add a footnote about how this will be handled.

Thoughts?

**Comment by fritzek** [comment]
I suggest to have a footnote about the handling as follows:

```
The benefit may be claimed, if the value of the subscription reaches the one off package value.
```

**Comment by svenfuchs** [comment]
After lots of discussion with various people we decided to simply remove the "big" and "huge" packages (and rename the remaining packages to small, medium, big)
