### ISSUE TITLE
Ask donor is a company for Big and Huge packs

### ISSUE THREAD

**Issue by fritzek** [travis-ci/travis-crowd#94]
We should ask the donor if he is a company. If so and he comes from Germany we can add VAT on top of pack value.
For privates it would be unfair.

**Comment by fritzek** [comment]
Suggestion: add a note "You're able to deduct VAT?" if country=Germany and add a Yes/No-Switch (default= Yes - as we expect mostly companies to choose Big or Huge) and calc VAT on top of pack value.

**Comment by rkh** [comment]
Note: If answer is yes, we'll need the address.

**Comment by rkh** [comment]
done and on staging
