### ISSUE TITLE
List VAT in Invoices

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-crowd#95]
Probably our VAT ID, too.

**Comment by fritzek** [comment]
Note to myself: location for VAT handling is regulated by UStG § 3g (Ort der Lieferung von Gas, Elektrizität, Wärme oder Kälte)

**Comment by fritzek** [comment]
VAT law §14 (http://www.gesetze-im-internet.de/ustg_1980/__14.html)

(4) Eine Rechnung muss folgende Angaben enthalten:
1. den vollständigen Namen und die vollständige Anschrift des leistenden Unternehmers und des Leistungsempfängers,
2. die dem leistenden Unternehmer vom Finanzamt erteilte Steuernummer oder die ihm vom Bundeszentralamt für Steuern erteilte Umsatzsteuer-Identifikationsnummer,
3. das Ausstellungsdatum,
4. eine fortlaufende Nummer mit einer oder mehreren Zahlenreihen, die zur Identifizierung der Rechnung vom Rechnungsaussteller einmalig vergeben wird (Rechnungsnummer),
5. die Menge und die Art (handelsübliche Bezeichnung) der gelieferten Gegenstände oder den Umfang und die Art der sonstigen Leistung,
6. den Zeitpunkt der Lieferung oder sonstigen Leistung; in den Fällen des Absatzes 5 Satz 1 den Zeitpunkt der Vereinnahmung des Entgelts oder eines Teils des Entgelts, sofern der Zeitpunkt der Vereinnahmung feststeht und nicht mit dem Ausstellungsdatum der Rechnung übereinstimmt,
7. das nach Steuersätzen und einzelnen Steuerbefreiungen aufgeschlüsselte Entgelt für die Lieferung oder sonstige Leistung (§ 10) sowie jede im Voraus vereinbarte Minderung des Entgelts, sofern sie nicht bereits im Entgelt berücksichtigt ist,
8. den anzuwendenden Steuersatz sowie den auf das Entgelt entfallenden Steuerbetrag oder im Fall einer Steuerbefreiung einen Hinweis darauf, dass für die Lieferung oder sonstige Leistung eine Steuerbefreiung gilt und
9. in den Fällen des § 14b Abs. 1 Satz 5 einen Hinweis auf die Aufbewahrungspflicht des Leistungsempfängers.

**Comment by fritzek** [comment]
english translation of above law text:
we have to put on a regular VAT invoice the following:
1. Name and complete address from Travis and the receiver
2. Travis tax number or VAT ID
3. date of invoice
4. sequential unique number (can include characters)
5. amount and type of delivery or service
6. date of delivery or service
7. - not relevant as we just have one tax rate - we only have to display the net amount, tax amount and gross amount
8. the used tax rate - in our case either 19% or 0%
9. - not applicable -
