### ISSUE TITLE
No option to fill in a custom amount for donating

### ISSUE THREAD

**Issue by dhiemstra** [travis-ci/travis-crowd#98]
This might be important. Me for example wanted to donate a couple of dolars to travis.
I pressed the $1 link and went to the form, filled this in and after submit it told me i donated $1.

I wanted to donate more than $1 but i just left after this because i couldn't be bothered to go back again.

**Comment by rkh** [comment]
We have thought about this and might add it (esp if there is more demand for it), but we didn't want it blocking our launch. Donating again is way easier than just donating once, though that is not obvious unless you try. If you have the time, we'd be happy about patches.

**Comment by dhiemstra** [comment]
Discussed this with Josh as well, he suggested me to use a plan but for me $10 is to much (yes call me greedy) for something that i see as a super cool project but don't use myself. I think a support option between $1-5 would be nice.

When i have some spare time i might take a look soon but no promisses :)

**Comment by rkh** [comment]
Too many options might be overwhelming, too. We could add it as text link, like the $1 option.
